apiVersion: v1
kind: Service
metadata:
  name: sample-spring-boot-app
  labels:
    app: sample-spring-boot-app
spec:
  type: LoadBalancer
  selector:
    app: sample-spring-boot-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
